### ISSUE TITLE
Move to suitcss org?

### ISSUE THREAD

**Issue by simonsmith** [simonsmith/gulp-suitcss#1]
Hey,

We've been (and currently still are) making various improvements and changes to the suitcss-preprocessor. Would you be open to moving this to the suitcss org (and adding me to npm) so that we can keep it up to date?

**Comment by Casear** [comment]
Hi ,
that's ok. since I already move to postcss.
I will transfer all the permission to you.

**Comment by simonsmith** [comment]
Thanks! Appreciate it
