### ISSUE TITLE
NPM Warning with 2.0.0

### ISSUE THREAD

**Issue by rocketspops** [simonsmith/gulp-suitcss#3]
Hey @simonsmith thanks for the update! FYI, upon installing I get the following error:

``` bash
npm WARN stylelint-config-suitcss@8.0.0 requires a peer of stylelint@^7.0.1 but none was installed.
```

Is it safe to ignore this?

**Comment by simonsmith** [comment]
Do you have a lower version of stylelint already installed in your project? The only way I could replicate this was to install `stylelint@7.0.0` in the same project.

Upgrading to stylelint `7.0.1` or greater should resolve it.

**Comment by rocketspops** [comment]
Yup, upgrading fixed this. Thanks.
