### ISSUE TITLE
Is there a way to process only changed files or dependencies?

### ISSUE THREAD

**Issue by rocketspops** [simonsmith/gulp-suitcss#5]
Hey @simonsmith,

The `suitcss` CLI tool has a handy watcher built in:

```bash
-w, --watch
```
In my `gulp` task, I'm using [`changed-in-place`](https://www.npmjs.com/package/gulp-changed-in-place) to process only those files that have changed since the last time the task was run: 

```javascript
gulp.task('compile:css', function() {
  return gulp.src(paths.styles)
  .pipe(changedInPlace({ firstPass: true }))
  .pipe(print(function(filepath) { return "Compiled " + "'" + filepath + "'"; }))
  .pipe(suitcss({
    'postcss-easy-import': { prefix: "_" },
    'postcss-calc': { precision: 0 },
    'postcss-custom-properties': { preserve: "computed" },
    stylelint: {
      extends: 'stylelint-config-suitcss',
      rules: {
        'at-rule-empty-line-before': [ 'always',
          { 'ignore': [ 'all-nested', 'blockless-after-same-name-blockless' ] }
        ]
      }
    }
  }
  ))
  .pipe(rename(function(path){
    path.dirname += '/../';
    path.basename = path.basename.replace(/--suit/, '');
    return path
  }))
  .pipe(gulp.dest('src'));
});
```
However, I'm having trouble figuring out how to process files when their dependencies (via `@import`) have changed. 

Is this functionality somehow built into  the `suitcss` preprocessor? 

Thanks,
Billy

**Comment by simonsmith** [comment]
Hey,

Yes it is. I'm not sure how it might help with `changedInPlace` but I'll point you in the right direction.

Whenever the preprocessor runs it gets hold of all the imported files from `postcss-import` and calls a global `watchCSS` function with them. Seen here - https://github.com/suitcss/preprocessor/blob/master/lib/index.js#L191-L195

The suitcss CLI uses `chokidar` (the same tool used by gulp I think) to watch the input file, but it also defines a `watchCSS` function that updates the watch list with all the files mentioned earlier. As seen here - https://github.com/suitcss/preprocessor/blob/master/bin/suitcss#L95-L111 That allows it to react to changes in a dependency.

By using that hook you can update any watch task you like. My `gulp` skills are rusty so not sure how that might apply.

**Comment by rocketspops** [comment]
Hey @simonsmith,

Thanks for the tip. I was able to accomplish what I wanted using [`gulp-dependencies-changed`](https://www.npmjs.com/package/gulp-dependencies-changed):

```javascript
gulp.task('compile:css', function() {
  return gulp.src(paths.suit)
  .pipe(changed({
    matcher: /@import ['"]?((?!suit)[^'"]+)['"]?;/g,
    dest: function(srcRelPath, srcBasePath) {
      return rename(srcRelPath, function(fileObj) {
        return {
          dirname: path.join('src/' + (fileObj.dirname + "/../")),
          basename: fileObj.basename.replace(/--suit/, ''),
          extname: '.css'
        };
      });
    }
  }))
  .pipe(suitcss({
    'postcss-calc': { precision: 0 },
    'postcss-custom-properties': { preserve: "computed" },
    stylelint: {
      extends: 'stylelint-config-suitcss',
      rules: {
        'at-rule-empty-line-before': [ 'always',
          { 'ignore': [ 'all-nested', 'blockless-after-same-name-blockless' ] }
        ]
      }
    }
  }
  ))
  .pipe(gulpRename(function(path){
    path.dirname += '/../';
    path.basename = path.basename.replace(/--suit/, '');
    return path
  }))
  .pipe(print(function(filepath) {
    return "Compiled " + "'" + filepath + "'";
  }))
  .pipe(gulp.dest('src'));
});
```
There may be a better way that ties into the built-in functionality of the `watchCSS` function, but I'll admit, figuring that out is a bit beyond my skill level :/. 

Thanks!
